config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  require 'sidekiq/web' 
  mount Sidekiq::Web => '/jobs'
  
  get "/documents/:id/image" => "documents#show_image", as: :image
  get "/documents/import" => "documents#import_now", as: :import_now

  resources :tasks, :documents

  root 'pages#main'
end

app/models/document.rb
require "base64"
require 'rmagick'
include Magick

class Document < ApplicationRecord

  validates :image, presence: true
  validates :filename, presence: true
  validates :content_type, presence: true

  default_scope { order('created_at desc') }
  scope :unprocessed, -> { where(ocr_text: nil) }

  def initialize(params = {})
    puts "Instantiating from the web: #{params[:file]}"
    file = params.delete(:file)
    super
    if file
      Document.generate_doc(self, file.original_filename, file.tempfile)
    end
  end

  def self.from_file(filename)
    puts "Instantiating from file: #{filename}"
    doc = Document.new
    file = File.open(filename, 'r')
    Document.generate_doc(doc, filename, file)
  end

  def self.generate_doc(doc, filename, file)
    if file
      doc.filename = doc.sanitize_filename(filename)
      puts "Encoding base64 data"
      doc.content_type, doc.image = Document.generate_base_64(file.path)
    end    
    doc
  end

  def miniature
    unless self[:miniature]
      mini = Image.from_blob(Base64.decode64(self.image)).first
      mini = mini.resize_to_fit(100, 100)
      mini.format = "PNG"
      mini_data = mini.to_blob
      self.update_attributes!(miniature: Base64.encode64(mini_data))
    end
    self[:miniature]
  end

  def icon
    unless self[:icon]
      mini = Image.from_blob(Base64.decode64(self.image)).first
      mini = mini.resize_to_fit(16, 16)
      mini.format = "PNG"
      mini_data = mini.to_blob
      self.update_attributes!(icon: Base64.encode64(mini_data))
    end
    self[:icon]
  end

  def self.generate_base_64(filename)
    img = Image.read(filename) do
      self.quality = 100
      self.density = '300'
    end.first
    img.format = "PNG"
    img = img.resize_to_fit(2000, 2000)
    img_data = img.to_blob
    return "image/png", Base64.encode64(img_data)
  end

  def text_as_html
    return '' unless ocr_text?
    ocr_text.gsub("\n", '<br/>')
            .gsub("\r", '<br/>')
            .html_safe
  end

  def sanitize_filename(filename)
    # Get only the filename, not the whole path (for IE)
    # Thanks to this article I just found for the tip: http://mattberther.com/2007/10/19/uploading-files-to-a-database-using-rails
    return File.basename(filename)
  end
end

app/controllers/documents_controller.rb
include DocumentsHelper

class DocumentsController < SecureController
  before_action :set_document, only: [:show, :show_image, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @q = Document.ransack(params[:q])
    @documents = @q.result(distinct: true).page(params[:page]).per(10)
    @files_to_be_processed = Dir["#{ENV['IMAGES_IMPORT_FOLDER']}/*"]
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  def show_image
    send_data Base64.decode64(@document.image), type: @document.content_type, disposition: "inline"
  end

  def import_now
    ImageProcessingWorker.perform_async
    # import_images_and_ocr
    flash[:success] = 'Running background import task...'
    redirect_to documents_url
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:file)
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper

  def miniature_for(doc)
    "<img src=\"data:image/png;base64,#{doc.miniature}\" />".html_safe
  end

  def icon_for(doc)
    "<img src=\"data:image/png;base64,#{doc.icon}\" />".html_safe
  end

  def import_images_and_ocr
    puts "Processing images from : #{ENV['IMAGES_IMPORT_FOLDER']}"

    # Read images from import folder
    Dir["#{ENV['IMAGES_IMPORT_FOLDER']}/*"].each do |f|
      if Document.from_file(f).save
        File.delete(f)
      end
    end

    # OCR those that need to be ocr'ed
    Document.unprocessed.each do |d|
      d.update_attributes!(ocr_text: ocr_from_google(d.image))
    end
  end

  def ocr_from_google(base64_data)
    # Stuff we need
    api_key = ENV['GOOGLE_VISION_API_KEY']
    content_type = "Content-Type: application/json"
    url = "https://vision.googleapis.com/v1/images:annotate?key=#{api_key}"
    data = {
      "requests": [
        {
          "image": {
            "content": base64_data
          },
          "features": [
            {
              "type": "TEXT_DETECTION",
              "maxResults": 1
            }
          ]
        }
      ]
    }.to_json

    # Make the request
    url = URI(url)
    req = Net::HTTP::Post.new(url, initheader = {'Content-Type' =>'application/json'})
    req.body = data
    res = Net::HTTP.new(url.host, url.port)
    res.use_ssl = true

    # res.set_debug_output $stderr

    detected_text = ""
    res.start do |http| 
      puts "Querying Google for image: #{ARGV[0]}"
      resp = http.request(req)
      json = JSON.parse(resp.body)
      if json && json["responses"] && json["responses"][0]["textAnnotations"] && json["responses"][0]["textAnnotations"][0]["description"]
        detected_text = json["responses"][0]["textAnnotations"][0]["description"]
      else
        puts "Ooopsie from Google:"
        pp json
      end
    end

    puts "Google says the image is: #{detected_text}"
    detected_text
  end
end

app/views/documents/_form.html.slim
= form_for(document) do |f|
  - if document.errors.any?
    div#error_explanation
      h2 #{pluralize(document.errors.count, "error")} prohibited this document from being saved:

      ul
        - document.errors.full_messages.each do |message|
          li = message

  div.field
    = f.label :file
    = f.file_field :file

  div.actions
    = f.submit

app/views/documents/edit.html.slim
h1 Editing Document

= render 'form', document: @document

= link_to 'Show', @document 
= " | "
= link_to 'Back', documents_path

app/views/documents/index.html.slim
p#notice = notice

h1 Documents

- if @documents.count > 0

  = search_form_for @q do |f|
    = f.label :ocr_text_cont
    = f.search_field :ocr_text_cont
    = f.submit

  table
    thead
      tr
        th
        th Date
        th Filename
        th Content Type
        th Processed?
        th colspan="2"
      
    tbody
      - @documents.each do |document|
        tr
          td 
            a href="#{image_url document}"
              = icon_for document
          td = document.created_at.stamp('2016-02-31')
          td
            = link_to document.filename, document
          td = document.content_type
          td = document.ocr_text?
          td = link_to 'Show', document
          td = link_to 'Edit', edit_document_url(document)
          td = link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' }
  br
  = paginate @documents

- if @files_to_be_processed.count > 0
  h3 Files waiting to be imported:
  ul
    - @files_to_be_processed.each do |f|
      li = f.split('/').last

= link_to 'New Document', new_document_url
= " | "
= link_to 'Import Now', import_now_url

app/views/documents/new.html.slim
h1 New Document

= render 'form', document: @document

= link_to 'Back', documents_path

app/views/documents/show.html.slim
p#notice = notice

p
  strong Date:
  br
  = @document.created_at

p
  strong Content Type:
  br
  = @document.content_type

p
  a href="#{image_url(@document)}"
    = miniature_for @document

p 
  strong OCR Text:
  br
  = @document.text_as_html

= link_to 'Edit', edit_document_path(@document)
= " | "
= link_to 'Back', documents_path 